### ISSUE TITLE
Membership Application

### ISSUE THREAD

**Issue by kou3seki** [UESTC-TOUHOU/Community#5]
Hi! 欢迎加入 UESTC幻想乡  👏，请填写以下信息：

- 名字：光棱
- 厨谁：苗
- 有无同人贡献:无

⚠️ 提交 Issue 后，请在 [MEMBERS](https://github.com/UESTC-TOUHOU/Community/blob/main/MEMBERS) 文件末尾加入你的 GitHub ID 并提交 PR，等待 Maintainer 的审核

**Comment by wray-lee** [comment]
请提交pr
